# Generated by Django 6.0.5 on 2026-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_hr", "0002_documentrh_evaluation_formation_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="role",
            field=models.CharField(
                choices=[
                    ("PDG", "Président Directeur Général"),
                    ("RH", "Responsable RH"),
                    ("EMPLOYE", "Employé"),
                ],
                default="EMPLOYE",
                max_length=20,
            ),
        ),
    ]
