# Generated by Django 6.0.5 on 2026-05-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_hr", "0003_employe_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordonnes",
                to="core_hr.employe",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Super Administrateur"),
                    ("RH", "Administrateur RH"),
                    ("MANAGER", "Manager / Chef d'équipe"),
                    ("EMPLOYE", "Employé"),
                    ("CANDIDAT", "Candidat"),
                    ("AUDITEUR", "Auditeur Externe"),
                ],
                default="EMPLOYE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NoteDeFrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "justificatif",
                    models.FileField(blank=True, null=True, upload_to="frais/"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REJETE", "Rejeté"),
                            ("REMBOURSE", "Remboursé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_frais",
                        to="core_hr.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_limite", models.DateField()),
                ("progression", models.IntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="core_hr.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="core_hr.employe",
                    ),
                ),
            ],
        ),
    ]
