# Generated by Django 6.0.5 on 2026-05-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_hr", "0004_employe_manager_alter_employe_role_notedefrais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointage",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Présent"),
                    ("RETARD", "En retard"),
                    ("ABSENT", "Absent"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
    ]
