# Generated by Django 6.0.5 on 2026-05-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nb_jours_max", models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("motif", models.TextField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente"),
                            ("APPROUVE", "Approuvé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_conge",
                        to="core_hr.employe",
                    ),
                ),
                (
                    "type_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leaves.typeconge",
                    ),
                ),
            ],
        ),
    ]
