# Generated by Django 6.0.5 on 2026-05-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_hr", "0003_employe_role"),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
                (
                    "nb_jours_total",
                    models.DecimalField(decimal_places=1, default=30.0, max_digits=5),
                ),
                (
                    "nb_jours_pris",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conge",
                        to="core_hr.employe",
                    ),
                ),
                (
                    "type_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaves.typeconge",
                    ),
                ),
            ],
        ),
    ]
