# Generated by Django 6.0.5 on 2026-05-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubriquePaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=100)),
                (
                    "type_rubrique",
                    models.CharField(
                        choices=[
                            ("GAIN", "Gain / Prime"),
                            ("RETENUE", "Retenue / Cotisation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "taux_salarial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taux_patronal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("est_fixe", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BulletinPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.DateField()),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                ("salaire_brut", models.DecimalField(decimal_places=2, max_digits=12)),
                ("salaire_net", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="bulletins/"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_hr.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailBulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "part_salariale",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "part_patronale",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="payroll.bulletinpaie",
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.rubriquepaie",
                    ),
                ),
            ],
        ),
    ]
