# Generated by Django 6.0.5 on 2026-05-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
            ],
        ),
        migrations.CreateModel(
            name="OffreEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_publication", models.DateField(auto_now_add=True)),
                ("est_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_postulation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVEAU", "Nouveau"),
                            ("ENTRETIEN", "Entretien"),
                            ("OFFRE", "Offre"),
                            ("REJETE", "Rejeté"),
                            ("EMBAUCHE", "Embauché"),
                        ],
                        default="NOUVEAU",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="recruitment.candidat",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="recruitment.offreemploi",
                    ),
                ),
            ],
        ),
    ]
